# Generated by Django 4.2.7 on 2023-11-29 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_alter_recipe_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='food_photo',
            field=models.ImageField(blank=True, null=True, upload_to='recipes/recipe_photos/'),
        ),
    ]
